
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.block
{
/// <summary>
/// 星图章节表(22张塔罗牌按主线拆4章;整章全部集齐发大奖)
/// </summary>
public partial class TbTarotChapter
{
    private readonly System.Collections.Generic.Dictionary<int, TarotChapter> _dataMap;
    private readonly System.Collections.Generic.List<TarotChapter> _dataList;
    
    public TbTarotChapter(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, TarotChapter>();
        _dataList = new System.Collections.Generic.List<TarotChapter>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            TarotChapter _v;
            _v = TarotChapter.DeserializeTarotChapter(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, TarotChapter> DataMap => _dataMap;
    public System.Collections.Generic.List<TarotChapter> DataList => _dataList;

    public TarotChapter GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public TarotChapter Get(int key) => _dataMap[key];
    public TarotChapter this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
