
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.currency
{
/// <summary>
/// 数值底层货币表
/// </summary>
public partial class TbCurrency
{
    private readonly System.Collections.Generic.Dictionary<int, Currency> _dataMap;
    private readonly System.Collections.Generic.List<Currency> _dataList;
    
    public TbCurrency(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, Currency>();
        _dataList = new System.Collections.Generic.List<Currency>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            Currency _v;
            _v = Currency.DeserializeCurrency(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, Currency> DataMap => _dataMap;
    public System.Collections.Generic.List<Currency> DataList => _dataList;

    public Currency GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public Currency Get(int key) => _dataMap[key];
    public Currency this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
