
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class GiftFixed : Luban.BeanBase
{
    public GiftFixed(ByteBuf _buf) 
    {
        AutoId = _buf.ReadInt();
        RewardId = _buf.ReadInt();
        ItemId = _buf.ReadInt();
        Num = _buf.ReadInt();
    }

    public static GiftFixed DeserializeGiftFixed(ByteBuf _buf)
    {
        return new GiftFixed(_buf);
    }

    /// <summary>
    /// 行主键(index=auto_id)
    /// </summary>
    public readonly int AutoId;
    /// <summary>
    /// 所属礼包组id(同reward_id=一份固定礼包)
    /// </summary>
    public readonly int RewardId;
    /// <summary>
    /// 道具id(指向item.TbItemDef)
    /// </summary>
    public readonly int ItemId;
    /// <summary>
    /// 该道具数量
    /// </summary>
    public readonly int Num;
   
    public const int __ID__ = -1743787004;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "autoId:" + AutoId + ","
        + "rewardId:" + RewardId + ","
        + "itemId:" + ItemId + ","
        + "num:" + Num + ","
        + "}";
    }
}

}
