
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.item
{
/// <summary>
/// 固定礼包表(塔罗解锁等固定发奖:同reward_id聚合为一份礼包,全发不抽)
/// </summary>
public partial class TbGiftFixed
{
    private readonly System.Collections.Generic.Dictionary<int, GiftFixed> _dataMap;
    private readonly System.Collections.Generic.List<GiftFixed> _dataList;
    
    public TbGiftFixed(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, GiftFixed>();
        _dataList = new System.Collections.Generic.List<GiftFixed>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            GiftFixed _v;
            _v = GiftFixed.DeserializeGiftFixed(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.AutoId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, GiftFixed> DataMap => _dataMap;
    public System.Collections.Generic.List<GiftFixed> DataList => _dataList;

    public GiftFixed GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public GiftFixed Get(int key) => _dataMap[key];
    public GiftFixed this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
