
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class Num : Luban.BeanBase
{
    public Num(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Desc = _buf.ReadString();
        FuncName = _buf.ReadString();
        NumType = (num.ENumType)_buf.ReadInt();
    }

    public static Num DeserializeNum(ByteBuf _buf)
    {
        return new Num(_buf);
    }

    /// <summary>
    /// 资源id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 功能命名(服务器用)
    /// </summary>
    public readonly string FuncName;
    /// <summary>
    /// 资源类型
    /// </summary>
    public readonly num.ENumType NumType;
   
    public const int __ID__ = 78694;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "desc:" + Desc + ","
        + "funcName:" + FuncName + ","
        + "numType:" + NumType + ","
        + "}";
    }
}

}
