
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RedeemCode : Luban.BeanBase
{
    public RedeemCode(ByteBuf _buf) 
    {
        Code = _buf.ReadString();
        RewardBoxId = _buf.ReadInt();
        ExpireUnixMs = _buf.ReadLong();
        GlobalLimit = _buf.ReadInt();
    }

    public static RedeemCode DeserializeRedeemCode(ByteBuf _buf)
    {
        return new RedeemCode(_buf);
    }

    /// <summary>
    /// 兑换码(服务端trim+大写规整后为key)
    /// </summary>
    public readonly string Code;
    /// <summary>
    /// 奖励盒id(指向reward.TbRewardBox)
    /// </summary>
    public readonly int RewardBoxId;
    /// <summary>
    /// 过期时刻(Unix毫秒UTC,0=永不过期)
    /// </summary>
    public readonly long ExpireUnixMs;
    /// <summary>
    /// 全局发放上限(0=不限量)
    /// </summary>
    public readonly int GlobalLimit;
   
    public const int __ID__ = -473265719;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "code:" + Code + ","
        + "rewardBoxId:" + RewardBoxId + ","
        + "expireUnixMs:" + ExpireUnixMs + ","
        + "globalLimit:" + GlobalLimit + ","
        + "}";
    }
}

}
