
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.reward
{
/// <summary>
/// 奖励条目(单条奖励:类型+目标id+数量)
/// </summary>
public sealed partial class RewardEntry : Luban.BeanBase
{
    public RewardEntry(ByteBuf _buf) 
    {
        RewardType = (reward.ERewardType)_buf.ReadInt();
        TargetId = _buf.ReadInt();
        Amount = _buf.ReadInt();
    }

    public static RewardEntry DeserializeRewardEntry(ByteBuf _buf)
    {
        return new reward.RewardEntry(_buf);
    }

    /// <summary>
    /// 奖励类型-Currency货币/Item道具
    /// </summary>
    public readonly reward.ERewardType RewardType;
    /// <summary>
    /// 目标id-货币指TbNum/道具指TbItemDef
    /// </summary>
    public readonly int TargetId;
    /// <summary>
    /// 发放数量
    /// </summary>
    public readonly int Amount;
   
    public const int __ID__ = -61714908;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "rewardType:" + RewardType + ","
        + "targetId:" + TargetId + ","
        + "amount:" + Amount + ","
        + "}";
    }
}

}
