
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class RewardBox : Luban.BeanBase
{
    public RewardBox(ByteBuf _buf) 
    {
        BoxId = _buf.ReadInt();
        {int n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);Rewards = new System.Collections.Generic.List<reward.RewardEntry>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { reward.RewardEntry _e0;  _e0 = reward.RewardEntry.DeserializeRewardEntry(_buf); Rewards.Add(_e0);}}
    }

    public static RewardBox DeserializeRewardBox(ByteBuf _buf)
    {
        return new RewardBox(_buf);
    }

    /// <summary>
    /// 奖励盒子id-别处用它一把取整盒
    /// </summary>
    public readonly int BoxId;
    /// <summary>
    /// 奖励条目列表-整组固定全发
    /// </summary>
    public readonly System.Collections.Generic.List<reward.RewardEntry> Rewards;
   
    public const int __ID__ = -1128082436;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        foreach (var _e in Rewards) { _e?.ResolveRef(tables); }
    }

    public override string ToString()
    {
        return "{ "
        + "boxId:" + BoxId + ","
        + "rewards:" + Luban.StringUtil.CollectionToString(Rewards) + ","
        + "}";
    }
}

}
