
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.reward
{
/// <summary>
/// 奖励盒子表(一行一盒/box_id取整盒奖励)
/// </summary>
public partial class TbRewardBox
{
    private readonly System.Collections.Generic.Dictionary<int, RewardBox> _dataMap;
    private readonly System.Collections.Generic.List<RewardBox> _dataList;
    
    public TbRewardBox(ByteBuf _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, RewardBox>();
        _dataList = new System.Collections.Generic.List<RewardBox>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            RewardBox _v;
            _v = RewardBox.DeserializeRewardBox(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BoxId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, RewardBox> DataMap => _dataMap;
    public System.Collections.Generic.List<RewardBox> DataList => _dataList;

    public RewardBox GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public RewardBox Get(int key) => _dataMap[key];
    public RewardBox this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}
