
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// BlockBlast动态权重tier表
    /// </summary>
    public block.TbWeightCfg TbWeightCfg {get; }
    /// <summary>
    /// 数值底层货币表
    /// </summary>
    public currency.TbCurrency TbCurrency {get; }
    /// <summary>
    /// 道具定义表
    /// </summary>
    public item.TbItemDef TbItemDef {get; }
    /// <summary>
    /// 随机礼包池表
    /// </summary>
    public item.TbGiftRandom TbGiftRandom {get; }
    /// <summary>
    /// 自选礼包池表
    /// </summary>
    public item.TbGiftSelect TbGiftSelect {get; }
    /// <summary>
    /// 头像与头像框表
    /// </summary>
    public avatar.TbAvatar TbAvatar {get; }
    /// <summary>
    /// rank board table (multi-tier per id)
    /// </summary>
    public rank.TbRank TbRank {get; }
    /// <summary>
    /// 全局零散参数配置表(键值型,value按需解析)
    /// </summary>
    public global.TbGlobal TbGlobal {get; }
    /// <summary>
    /// 订单池表(池序=id升序;奖励直配值;碎片=塔罗收集掉落源)
    /// </summary>
    public block.TbMergeOrder TbMergeOrder {get; }
    /// <summary>
    /// 塔罗牌收集表(22张大阿卡纳;碎片凑齐手动合成)
    /// </summary>
    public block.TbTarotCard TbTarotCard {get; }
    /// <summary>
    /// 音频资源配置表(数据驱动播放)
    /// </summary>
    public audio.TbAudio TbAudio {get; }
    /// <summary>
    /// 女神满档领取奖励表(行=等级+数量;元素类型运行时取当前未交付订单所需类型)
    /// </summary>
    public block.TbGoddessReward TbGoddessReward {get; }
    /// <summary>
    /// 星图章节表(22张塔罗牌按主线拆4章;整章全部集齐发大奖)
    /// </summary>
    public block.TbTarotChapter TbTarotChapter {get; }
    /// <summary>
    /// 奖励盒子表(一行一盒/box_id取整盒奖励)
    /// </summary>
    public reward.TbRewardBox TbRewardBox {get; }
    /// <summary>
    /// 通用兑换码表(服务端权威码表,code为key,仅server组不进客户端包)
    /// </summary>
    public redeem.TbRedeemCode TbRedeemCode {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbWeightCfg = new block.TbWeightCfg(loader("block_tbweightcfg"));
        TbCurrency = new currency.TbCurrency(loader("currency_tbcurrency"));
        TbItemDef = new item.TbItemDef(loader("item_tbitemdef"));
        TbGiftRandom = new item.TbGiftRandom(loader("item_tbgiftrandom"));
        TbGiftSelect = new item.TbGiftSelect(loader("item_tbgiftselect"));
        TbAvatar = new avatar.TbAvatar(loader("avatar_tbavatar"));
        TbRank = new rank.TbRank(loader("rank_tbrank"));
        TbGlobal = new global.TbGlobal(loader("global_tbglobal"));
        TbMergeOrder = new block.TbMergeOrder(loader("block_tbmergeorder"));
        TbTarotCard = new block.TbTarotCard(loader("block_tbtarotcard"));
        TbAudio = new audio.TbAudio(loader("audio_tbaudio"));
        TbGoddessReward = new block.TbGoddessReward(loader("block_tbgoddessreward"));
        TbTarotChapter = new block.TbTarotChapter(loader("block_tbtarotchapter"));
        TbRewardBox = new reward.TbRewardBox(loader("reward_tbrewardbox"));
        TbRedeemCode = new redeem.TbRedeemCode(loader("redeem_tbredeemcode"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbWeightCfg.ResolveRef(this);
        TbCurrency.ResolveRef(this);
        TbItemDef.ResolveRef(this);
        TbGiftRandom.ResolveRef(this);
        TbGiftSelect.ResolveRef(this);
        TbAvatar.ResolveRef(this);
        TbRank.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbMergeOrder.ResolveRef(this);
        TbTarotCard.ResolveRef(this);
        TbAudio.ResolveRef(this);
        TbGoddessReward.ResolveRef(this);
        TbTarotChapter.ResolveRef(this);
        TbRewardBox.ResolveRef(this);
        TbRedeemCode.ResolveRef(this);
    }
}

}
