
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// BlockBlast动态权重tier表
    /// </summary>
    public block.TbWeightCfg TbWeightCfg {get; }
    /// <summary>
    /// 数值底层货币表
    /// </summary>
    public num.TbNum TbNum {get; }
    /// <summary>
    /// 道具定义表
    /// </summary>
    public item.TbItemDef TbItemDef {get; }
    /// <summary>
    /// 随机礼包池表
    /// </summary>
    public item.TbGiftRandom TbGiftRandom {get; }
    /// <summary>
    /// 自选礼包池表
    /// </summary>
    public item.TbGiftSelect TbGiftSelect {get; }
    /// <summary>
    /// 头像与头像框表
    /// </summary>
    public avatar.TbAvatar TbAvatar {get; }
    /// <summary>
    /// 通用邮件模板表
    /// </summary>
    public mail.TbMail TbMail {get; }
    /// <summary>
    /// 邮件全局配置表(单行)
    /// </summary>
    public mail.TbMailGlobal TbMailGlobal {get; }
    /// <summary>
    /// rank board table (multi-tier per id)
    /// </summary>
    public rank.TbRank TbRank {get; }
    /// <summary>
    /// 全局零散参数配置表(键值型,value按需解析)
    /// </summary>
    public global.TbGlobal TbGlobal {get; }
    /// <summary>
    /// 订单池表(池序=id升序;奖励直配值;碎片=塔罗收集掉落源)
    /// </summary>
    public block.TbMergeOrder TbMergeOrder {get; }
    /// <summary>
    /// 塔罗牌收集表(22张大阿卡纳;碎片凑齐手动合成)
    /// </summary>
    public block.TbTarotCard TbTarotCard {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbWeightCfg = new block.TbWeightCfg(loader("block_tbweightcfg"));
        TbNum = new num.TbNum(loader("num_tbnum"));
        TbItemDef = new item.TbItemDef(loader("item_tbitemdef"));
        TbGiftRandom = new item.TbGiftRandom(loader("item_tbgiftrandom"));
        TbGiftSelect = new item.TbGiftSelect(loader("item_tbgiftselect"));
        TbAvatar = new avatar.TbAvatar(loader("avatar_tbavatar"));
        TbMail = new mail.TbMail(loader("mail_tbmail"));
        TbMailGlobal = new mail.TbMailGlobal(loader("mail_tbmailglobal"));
        TbRank = new rank.TbRank(loader("rank_tbrank"));
        TbGlobal = new global.TbGlobal(loader("global_tbglobal"));
        TbMergeOrder = new block.TbMergeOrder(loader("block_tbmergeorder"));
        TbTarotCard = new block.TbTarotCard(loader("block_tbtarotcard"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbWeightCfg.ResolveRef(this);
        TbNum.ResolveRef(this);
        TbItemDef.ResolveRef(this);
        TbGiftRandom.ResolveRef(this);
        TbGiftSelect.ResolveRef(this);
        TbAvatar.ResolveRef(this);
        TbMail.ResolveRef(this);
        TbMailGlobal.ResolveRef(this);
        TbRank.ResolveRef(this);
        TbGlobal.ResolveRef(this);
        TbMergeOrder.ResolveRef(this);
        TbTarotCard.ResolveRef(this);
    }
}

}
