
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig
{
public sealed partial class TarotChapter : Luban.BeanBase
{
    public TarotChapter(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        CompleteReward = _buf.ReadInt();
    }

    public static TarotChapter DeserializeTarotChapter(ByteBuf _buf)
    {
        return new TarotChapter(_buf);
    }

    /// <summary>
    /// 章节id(1-4;主线递进)
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 章名(星图分段标题显示)
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 整章集齐大奖奖励id(引用礼包/奖励配置;0=无)
    /// </summary>
    public readonly int CompleteReward;
   
    public const int __ID__ = -1533024061;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        
        
        
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "completeReward:" + CompleteReward + ","
        + "}";
    }
}

}
